# Generated by Django 3.2 on 2024-04-14 19:23

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField()),
                ('name', models.CharField(max_length=156)),
                ('position', models.CharField(max_length=156)),
                ('fb', models.CharField(blank=True, max_length=156, null=True)),
                ('insta', models.CharField(blank=True, max_length=156, null=True)),
                ('linkedin', models.CharField(blank=True, max_length=156, null=True)),
                ('image', models.ImageField(upload_to='SEO')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=156)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Dentist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('h1', models.CharField(max_length=156)),
                ('slug', models.CharField(blank=True, max_length=1256, null=True)),
                ('page_name', models.CharField(blank=True, max_length=1256, null=True)),
                ('keyword', models.CharField(max_length=156)),
                ('description', models.CharField(max_length=900)),
                ('seo_title', models.CharField(max_length=156)),
                ('breadcrumb', models.CharField(max_length=156)),
                ('canonical', models.CharField(max_length=900)),
                ('og_type', models.CharField(max_length=156)),
                ('og_card', models.CharField(max_length=156)),
                ('og_site', models.CharField(max_length=156)),
                ('name', models.CharField(max_length=300)),
                ('title', models.CharField(max_length=300)),
                ('email', models.CharField(max_length=300)),
                ('contact', models.CharField(max_length=300)),
                ('bio', models.TextField(max_length=1300)),
                ('education', ckeditor_uploader.fields.RichTextUploadingField()),
                ('awards', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('experience', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('iframe', models.TextField(max_length=1300)),
                ('status', models.BooleanField(default=False)),
                ('treding', models.BooleanField(default=False)),
                ('in_home', models.BooleanField(default=False)),
                ('lat', models.TextField(max_length=1300)),
                ('long', models.TextField(max_length=1300)),
                ('schema', models.TextField(blank=True, max_length=15622, null=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.city')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=300)),
                ('short_code', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Specializations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tags', models.CharField(max_length=156)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='SEO')),
                ('name', models.CharField(max_length=156)),
                ('position', models.CharField(max_length=156)),
                ('fb', models.CharField(max_length=156)),
                ('insta', models.CharField(max_length=156)),
                ('twitter', models.CharField(max_length=156)),
                ('youtube', models.CharField(max_length=156)),
            ],
        ),
        migrations.CreateModel(
            name='Testimonials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='SEO')),
                ('name', models.CharField(max_length=156)),
                ('position', models.CharField(max_length=156)),
                ('review', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('star', models.CharField(max_length=300)),
                ('said', models.TextField(max_length=1300)),
                ('by', models.CharField(max_length=300)),
                ('date', models.CharField(max_length=300)),
                ('dentist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.dentist')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Dentist')),
                ('dentist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.dentist')),
            ],
        ),
        migrations.AddField(
            model_name='dentist',
            name='specializations',
            field=models.ManyToManyField(blank=True, null=True, to='account.Specializations'),
        ),
        migrations.AddField(
            model_name='dentist',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='User', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='city',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.location'),
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('h1', models.CharField(max_length=156)),
                ('slug', models.CharField(blank=True, max_length=1256, null=True)),
                ('page_name', models.CharField(blank=True, max_length=1256, null=True)),
                ('keyword', models.CharField(max_length=156)),
                ('description', models.CharField(max_length=900)),
                ('title', models.CharField(max_length=156)),
                ('breadcrumb', models.CharField(max_length=156)),
                ('canonical', models.CharField(max_length=900)),
                ('og_type', models.CharField(max_length=156)),
                ('og_card', models.CharField(max_length=156)),
                ('og_site', models.CharField(max_length=156)),
                ('image', models.ImageField(upload_to='SEO')),
                ('updated', models.DateField(auto_now=True)),
                ('blog_banner_lg', models.ImageField(blank=True, null=True, upload_to='Page Data')),
                ('blog_banner_sm', models.ImageField(blank=True, null=True, upload_to='Page Data')),
                ('published', models.DateField()),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
                ('edits', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.author')),
                ('category', models.ManyToManyField(to='account.Category')),
                ('tag', models.ManyToManyField(to='account.Tags')),
            ],
        ),
    ]
