# Generated by Django 3.2 on 2024-04-14 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dentist',
            name='profile',
            field=models.ImageField(blank=True, null=True, upload_to='SEO'),
        ),
    ]
