# Generated by Django 3.2 on 2024-04-14 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_dentist_sub_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='dentist',
            name='Fri',
            field=models.CharField(default='open', max_length=300),
        ),
        migrations.AddField(
            model_name='dentist',
            name='Mon',
            field=models.CharField(default='open', max_length=300),
        ),
        migrations.AddField(
            model_name='dentist',
            name='Sat',
            field=models.CharField(default='open', max_length=300),
        ),
        migrations.AddField(
            model_name='dentist',
            name='Sun',
            field=models.CharField(default='close', max_length=300),
        ),
        migrations.AddField(
            model_name='dentist',
            name='Thu',
            field=models.CharField(default='open', max_length=300),
        ),
        migrations.AddField(
            model_name='dentist',
            name='Tue',
            field=models.CharField(default='open', max_length=300),
        ),
        migrations.AddField(
            model_name='dentist',
            name='Wed',
            field=models.CharField(default='open', max_length=300),
        ),
    ]
