# Generated by Django 3.2 on 2024-04-14 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20240414_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='dentist',
            name='address',
            field=models.TextField(blank=True, max_length=15622, null=True),
        ),
    ]
