# Generated by Django 5.0.4 on 2024-04-25 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='dentist',
            name='Adaligner',
            field=models.CharField(default='1', max_length=300),
        ),
        migrations.AddField(
            model_name='dentist',
            name='Advance_zirconia',
            field=models.CharField(default='1', max_length=300),
        ),
        migrations.AddField(
            model_name='dentist',
            name='Coffee_table_book_Adimplant',
            field=models.CharField(default='1', max_length=300),
        ),
        migrations.AddField(
            model_name='dentist',
            name='USD_box',
            field=models.CharField(default='1', max_length=300),
        ),
        migrations.AddField(
            model_name='dentist',
            name='delivered_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
