# Generated by Django 5.0.1 on 2024-04-29 10:16

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_dentist_adaligner_dentist_advance_zirconia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dentist',
            name='Fri',
            field=models.CharField(blank=True, default='open', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='dentist',
            name='Mon',
            field=models.CharField(blank=True, default='open', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='dentist',
            name='Sat',
            field=models.CharField(blank=True, default='open', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='dentist',
            name='Sun',
            field=models.CharField(blank=True, default='close', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='dentist',
            name='Thu',
            field=models.CharField(blank=True, default='open', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='dentist',
            name='Tue',
            field=models.CharField(blank=True, default='open', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='dentist',
            name='Wed',
            field=models.CharField(blank=True, default='open', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='dentist',
            name='bio',
            field=models.TextField(blank=True, max_length=1300, null=True),
        ),
        migrations.AlterField(
            model_name='dentist',
            name='breadcrumb',
            field=models.CharField(blank=True, max_length=156, null=True),
        ),
        migrations.AlterField(
            model_name='dentist',
            name='canonical',
            field=models.CharField(blank=True, max_length=900, null=True),
        ),
        migrations.AlterField(
            model_name='dentist',
            name='description',
            field=models.CharField(blank=True, max_length=900, null=True),
        ),
        migrations.AlterField(
            model_name='dentist',
            name='education',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dentist',
            name='email',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='dentist',
            name='iframe',
            field=models.TextField(blank=True, max_length=1300, null=True),
        ),
        migrations.AlterField(
            model_name='dentist',
            name='keyword',
            field=models.CharField(blank=True, max_length=156, null=True),
        ),
        migrations.AlterField(
            model_name='dentist',
            name='lat',
            field=models.TextField(blank=True, max_length=1300, null=True),
        ),
        migrations.AlterField(
            model_name='dentist',
            name='long',
            field=models.TextField(blank=True, max_length=1300, null=True),
        ),
        migrations.AlterField(
            model_name='dentist',
            name='og_card',
            field=models.CharField(blank=True, max_length=156, null=True),
        ),
        migrations.AlterField(
            model_name='dentist',
            name='og_site',
            field=models.CharField(blank=True, max_length=156, null=True),
        ),
        migrations.AlterField(
            model_name='dentist',
            name='og_type',
            field=models.CharField(blank=True, max_length=156, null=True),
        ),
        migrations.AlterField(
            model_name='dentist',
            name='seo_title',
            field=models.CharField(blank=True, max_length=156, null=True),
        ),
    ]
