# Generated by Django 5.0.1 on 2024-04-29 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_alter_dentist_fri_alter_dentist_mon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dentist',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.city'),
        ),
    ]
