# Generated by Django 3.2 on 2024-08-20 15:26

import ckeditor_uploader.fields
import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_gallery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='fullname',
        ),
        migrations.AddField(
            model_name='contact',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 8, 20, 15, 26, 58, 323313, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='name',
            field=models.CharField(blank=True, max_length=1256, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.CharField(blank=True, max_length=1256, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(max_length=156),
        ),
        migrations.AlterField(
            model_name='contact',
            name='subject',
            field=models.CharField(max_length=156),
        ),
    ]
