# Generated by Django 3.2 on 2024-08-28 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_auto_20240820_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='dentist',
            name='state',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
